services:
  web:
    build: .
    container_name: medium_web
    command: sh /app/entry.dev.sh
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - medium
  db:
    image: postgres:15.2-alpine3.17
    container_name: medium_db
    healthcheck:
      test: [ "CMD", "sh", "-c", "psql -lqt --username=$SQL_USER | cut -d \\| -f 1 | grep -qw $SQL_DB" ]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 1s
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medium

volumes:
  postgres_data:

networks:
  medium: